version: "0.1.{build}"

clone_folder: C:\go-swagger
shallow_clone: true # for startup speed
pull_requests:
  do_not_increment_build_number: true

skip_tags: true
skip_branch_with_pr: true

# appveyor.yml
build: off

image:
  - Visual Studio 2019

environment:
  GO111MODULE: on
  GOPATH: c:\gopath

matrix:
  fast_finish: true

stack: go 1.15

before_test:
  - go mod download

test_script:
  # sanity test: basic build on windows works
  - set PATH=%GOPATH%\bin;%PATH%
  - go install github.com/go-swagger/go-swagger/cmd/swagger
  - swagger validate fixtures/bugs/2493/fixture-2492.json
  - swagger validate fixtures/bugs/2493/fixture-2493.json
  - swagger validate fixtures/bugs/2493/fixture-2492.yaml
  - swagger validate fixtures/bugs/2493/fixture-2493.yaml
  # full test suite
  - go test -timeout 20m ./...

deploy: off

notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    #incoming_webhook: https://hooks.slack.com/services/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
    channel: bots
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
