run:
  deadline: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen

linters:
  enable-all: true
  disable:
    - dupl
    - errcheck
    - gochecknoglobals
    - gocognit
    - gomnd
    - lll
    - unparam
    - wsl
