name: goreleaser
on: create

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        if: github.event.ref_type == 'tag'

      - uses: docker://goreleaser/goreleaser
        if: github.event.ref_type == 'tag'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          entrypoint: bash
          args: -c "git fetch --tags --prune --prune-tags --force && goreleaser release -f ci/.goreleaser.yml"
