language: go
go:
  - 1.16.x
env:
  global:
    - GO111MODULE: "on"
    - CGO_ENABLED: "0"
script:
  - make tidy
  - make generate
  - make test
  - git --no-pager diff && [[ 0 -eq $(git status --porcelain | wc -l) ]]
notifications:
  email:
    on_success: never
