language: go
go:
- 1.13.x
env:
  global:
  - GO111MODULE: 'on'
  - CGO_ENABLED: '0'
script:
  - go test -v ./...
  - go generate ./pkg/codegen/templates
  - go generate ./...
  - go mod tidy
  - git --no-pager diff && [[ 0 -eq $(git status --porcelain | wc -l) ]]
notifications:
  email:
    on_success: never
