name: CI
on: [push, pull_request]
jobs:
  Linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2    

    - name: Add $GOPATH/bin to PATH
      run: echo "::add-path::$(go env GOPATH)/bin"
      id: setup_path

    - name: Build
      run: make ci

  Windows:
    name: Windows
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2    

    - name: Add $GOPATH/bin to PATH
      shell: bash
      run: echo "::add-path::$(go env GOPATH)/bin"
      id: setup_path

    - name: Build
      run: make ci
