# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details

version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /go/src/github.com/mercari/go-circuitbreaker
    steps:
      - checkout
      - restore_cache:
          keys:
            - cb-v1-{{ checksum "go.mod" }}
      - run:
          command: go mod download
      - save_cache:
          key: cb-v1-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod
      - run: go test -v -race ./...
