on: [push, pull_request]
name: test and vet
jobs:
  main:
    strategy:
      matrix:
        go-version: [1.14, 1.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: install go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: checkout code
      uses: actions/checkout@v2
    - name: test
      run: make test
    - name: install vet tools
      if: matrix.go-version >= '1.16'
      run: make install-vet
    - name: vet
      if: matrix.go-version >= '1.16'
      run: make vet
